import { Book, Review } from './types';

export const BOOKS: Book[] = [
  {
    id: '地球끝의온실',
    title: '지구 끝의 온실 (한정판 에디션)',
    titleEn: 'Greenhouse at the End of the Earth (Special Edition)',
    author: '김초엽 지음',
    authorEn: 'Kim Cho-yeop',
    publisher: '허블',
    publisherEn: 'Hubble',
    pubDate: '2021-08-18',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC6tW8uJU7-TBU4uukT_srEKC0yIE1b7RUmj3icXDNLp4jZap6hCd3MZA1LOxpNWr4u720O0lvhgDh6eUgK0oW6sCVciAJea2ohHFhNLCT-41KEUyblsgE3-nJ7Yx09kzyzH0K36k4Mjzqb_5yG2IUCDIs5WCI6sMRoBThkv91xSYYqyqFAJb41X2Nqcq5_wkJduUBaF1XDsVLaLHRqKwOmtSMsTgzFmjbF1N6nZtwPNRKYqpxvtdE8j7M75d-vBZNwUN2_CY5O118D',
    price: 13500,
    originalPrice: 15000,
    rating: 9.6,
    reviewsCount: 312,
    category: 'Literature',
    desc: '어느 날 찾아온 더스트 사태로 멸망한 인류. 돔 시티 안팎의 격차가 커지고, 숲속에 버려진 온실에서 시작되는 마지막 인류의 구원 서사시. 김초엽 작가의 첫 장편소설이자 깊고 서정적인 SF의 마스터피스입니다.',
    descEn: 'A dust disaster collapses human civilization. An exploration of solidarity and hope emerging from a greenhouse at the end of the world, written by Kim Cho-yeop.',
    tag: '10% Off',
    details: {
      isbn: '9791190090018',
      pages: 392,
      tableOfContents: [
        '프롤로그: 더스트의 정원',
        '1부: 모스바나의 숲',
        '2부: 프림빌리지의 수호자',
        '3부: 지구 끝의 온실',
        '에필로그: 지지 않는 푸른 빛',
        '작가의 말'
      ],
      authorIntro: '포스텍 화학과를 졸업하고 생화학 석사를 마친 뒤 소설가가 되었습니다. 풍부한 과학적 지식 위에 따스한 감성과 단단한 문체를 얹어 아름다운 소설 세계를 창조합니다.',
      authorIntroEn: 'Graduated from POSTECH with a degree in chemistry. She creates warm, gorgeous science-fiction stories with scientific rigor and deep empathy.'
    }
  },
  {
    id: '불편한편의점',
    title: '불편한 편의점',
    titleEn: 'The Uncomfortable Convenience Store',
    author: '김호연 지음',
    authorEn: 'Kim Ho-yeon',
    publisher: '나무옆의자',
    publisherEn: 'Namu Yeop Uija',
    pubDate: '2021-04-20',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAMF2-vPWNbPAYHVpMexgSWJ7fxz3aKacHDynSg8SdrDqH0oQxYW8PJQI2SC8g2dyiJLqya5W96eeirkc5zzuDobOTt5Xti8dRrCT1h5CVSh3zMj9ZsnBwvKBhgijzxDW1mf5PXCJoazsnjmK4MhWbiWgzeaD_niLj0LeRtVK2TjTc8HZviOoGJDY4tjnvWofDkJw9XW4e_FJ7XwbE97p4m-IpHGGsCnHN9wyWTyvjfeSV0PTIP0jXvbrOqw-1vX3l9_kwww4tXdbWO',
    price: 14000,
    originalPrice: 14000,
    rating: 9.7,
    reviewsCount: 840,
    category: 'Literature',
    desc: '서울역에서 노숙생활을 하던 사내 ‘독고’가 청파동의 한 골목 편의점에서 야간 알바를 시작하며 벌어지는 이웃들의 따뜻하고 유쾌한 힐링 이야기입니다. 서로의 상처를 보듬고 살아가는 위로의 맛을 선사합니다.',
    descEn: 'A heartwarming story about a homeless man named Dokgo who gets a job at a local convenience store and slowly heals the lives of surrounding people.',
    tag: 'Best',
    details: {
      isbn: '9791161571188',
      pages: 268,
      tableOfContents: [
        '1. 독고와 할머니',
        '2. 제이에스 오브 제이에스',
        '3. 삼각김밥의 위로',
        '4. 원 플러스 원',
        '5. 참참참의 밤',
        '6. 오지랖과 진심',
        '7. 돌아온 자리',
        '8. 에필로그'
      ],
      authorIntro: '소설가이자 시나리오 작가입니다. 일상 속 따스한 시선과 살아 움직이는 캐릭터 창조로 수많은 독자들에게 진한 눈물과 웃음을 전해주고 있습니다.',
      authorIntroEn: 'A novelist and screenwriter. He writes everyday stories that connect deeply with modern readers, focusing on empathy and community healing.'
    }
  },
  {
    id: '트랜드코리아2024',
    title: '트렌드 코리아 2024',
    titleEn: 'Trend Korea 2024',
    author: '김난도 외 지음',
    authorEn: 'Kim Nan-do, et al.',
    publisher: '미래의창',
    publisherEn: 'Miraebooks',
    pubDate: '2023-10-12',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC5GLYrn7Eky45Q_YFEbaLpbXvxExNb6b1kp4yxUhryb4JAqIOqFkHQIN87v8WVtqgn84E014FDoprIZzaGGJ5ppuyYWTMLapdKkkOLdV_qRqfceAyUxcuzZPhgOHT5GQeHA-hM8FWOKEePRhrORBW03KjsQC-Xt9gzxU2iNBg6yFUHgbWNRQS4rWHBxYrrx8SDjQL6YJ_lSAa3zUfyT6_usblF92siMXR7eNGFl5X3mft5T6AG6sy8FtUxuC7qvUKKGMR9L6xMcsEo',
    price: 19000,
    originalPrice: 19000,
    rating: 9.1,
    reviewsCount: 154,
    category: 'Business',
    desc: '용의 해, 전 세계적인 인플레이션과 불황 속 대한민국 소비 트렌드를 한 눈에 조망하는 필독 지침서. 매해 신선한 키워드로 비즈니스 전략과 소비자의 심리 변화를 심도 깊게 진단해 줍니다.',
    descEn: 'An insightful exploration of consumer behaviors and marketplace trends in Korea for the year 2024. Curated by Professor Kim Nan-do.',
    tag: 'New',
    details: {
      isbn: '9788959897255',
      pages: 432,
      tableOfContents: [
        '서문: 불황 속 기회의 용꼬리를 잡아라',
        '2023년 소비트렌드 분석 및 회고',
        '드래곤 아이즈 (Dragon Eyes): 2024 대한민국 소비 트렌드 10대 키워드',
        '1. 분초사회 - 시간의 나노화',
        '2. 호모 프롬프트 - AI 세대의 기술 사용기',
        '3. 육각형인간 - 현대인의 끝없는 동경',
        '4. 버라이어티 가격 전략',
        '5. 도파밍 - 자극 추구 소비'
      ],
      authorIntro: '서울대학교 소비자학과 교수로 재직하며, 한국 트렌드를 가장 정밀하게 매핑해 내는 트렌드 연구자이자 베스트셀러 저자입니다.',
      authorIntroEn: 'A professor of Consumer Science at Seoul National University, widely popular for tracking trends and consulting corporations in Korea.'
    }
  },
  {
    id: '어둠의핵심',
    title: '어둠의 핵심 (세계문학전집)',
    titleEn: 'Heart of Darkness (World Literature Series)',
    author: '조셉 콘래드 지음',
    authorEn: 'Joseph Conrad',
    publisher: '민음사',
    publisherEn: 'Minumsa',
    pubDate: '2002-12-25',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAGCXuTks7rl3QE0-b_wauD1uWO7FlCAtq7Jvwescjf2_WcSWqE3JBCUOmgeXgOMYafBtIvm_t9HTQycRr6zuAg5NXS6mDGpr7DTl_8zuqb4n1H9a-rY21OSpDthCnnpRchYuZzknEuPGvyZUE32G88biJQdv1jKteFyq4K__pjMrFqpbK4RmI8ZJFpKNzfpbB_bU3XOG8_-weeZCgaWiLqsnQ98kAUKjn1z3Jkz0GUd_Kq12PBY3PcKLeUhX4OQOsDY7R2V7c1sCqv',
    price: 11000,
    originalPrice: 11000,
    rating: 9.3,
    reviewsCount: 95,
    category: 'Literature',
    desc: '문명의 이름으로 자행된 야만적 제국주의와 아프리카 콩고 정글 속 인간 내면에 도사린 광기, 탐욕을 묘사하여 고전 영문학에 깊은 족적을 남긴 마스터피스입니다.',
    descEn: 'A legendary masterwork charting Marlow s journey up the Congo River, confronting colonial barbarism and the dark abyss of human desire.',
    details: {
      isbn: '9788937460677',
      pages: 180,
      tableOfContents: [
        '어둠의 핵심',
        '작가의 서문',
        '조셉 콘래드 연보',
        '해설: 인간 문명의 허식과 야만적 내면'
      ],
      authorIntro: '폴란드 출신의 영국 소설가입니다. 청년기 대부분을 바다에서 선원으로 보내며 겪은 경험을 기반으로 인간 존재의 도덕적 갈등을 깊이 있게 담아냈습니다.',
      authorIntroEn: 'A Polish-British writer who spent years as a seaman. His works delve deeply into psychological depth and political choices under crises.'
    }
  },
  {
    id: '파친코1',
    title: '파친코 1',
    titleEn: 'Pachinko Vol. 1',
    author: '이민진 지음',
    authorEn: 'Min Jin Lee',
    publisher: '인플루엔셜',
    publisherEn: 'Influential',
    pubDate: '2022-07-27',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBytR-v5oOAjiLOdQbvEEFQMIN1NJ-Su1NOCQs4xmUG7hJSQ-DUH7v_lDtIQ0FwJZ2PqgeaMkHAG-fQzU6Z188LOs7hIiDBduHqQ5V0x_ZQA4cqulptBNGj0kVnh3eQODaU00wFLDMr_ZwBSD4MBmxZUWF8YhSh5BA9tZ2d4IheBcYK2FTP5hUX7WmP_gnKTxckfbdUA5_OemC1YwuTR0YVlA47WumfDnc9VnH-nCQ-mb8Un8QXiYvKa7RVCi4YhFGWAjr1n0CBqzUj',
    price: 15800,
    originalPrice: 15800,
    rating: 9.8,
    reviewsCount: 1250,
    category: 'Literature',
    desc: '4대에 걸친 자총적이고 치열한 이민 역사의 대서사시. 일제강점기 부산 영도에서 일본 오사카, 뉴욕까지 국경을 넘어 생존해 나간 한인 이민자들의 삶 복원소설.',
    descEn: 'A sweeping saga of a Korean family immigrating to Japan across four generations. An epic story of identity, resilience, and survival.',
    details: {
      isbn: '9791191054378',
      pages: 360,
      tableOfContents: [
        '1부 - 고향 고양 (1910-1933)',
        '2부 - 조국 없는 사랑 (1933-1953)',
        '추천의 글들',
        '제작 후기'
      ],
      authorIntro: '서울에서 태어나 7세 때 미국으로 이민을 갔습니다. 예일대에서 역사학을 전공하고 변호사로 일하다 전업작가가 되었으며, 전 미국도서상 최종 후보에 올랐습니다.',
      authorIntroEn: 'Born in Seoul, moved to New York at 7. Graduated Yale, worked as an attorney, and became a world-renowned novelist, capturing immigrant life.'
    }
  },
  {
    id: '소년이온다',
    title: '소년이 온다',
    titleEn: 'Human Acts',
    author: '한강 지음',
    authorEn: 'Han Kang',
    publisher: '창비',
    publisherEn: 'Changbi',
    pubDate: '2014-05-19',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAHST7k-EpbEGbiSPvu-T13smJrLa7KdBpguD0Z_z3hCHl_OE8lWNRxftvq96ZKrwb4TOVwMDa5OJGOEH1JYeKdo0ET6eFZxg_7zKbqZkyU_KhqfC3-U9_j1dvz0L4LhGlnANidQF58Z2Sv0CuxbzGI78GbenfwMGvnB_icbLxn0wsn_J2eFZ5gurtPr8dVAI7YZUtPvw-NzHX7zJggoz-ULTeCfyKBDLme2ht8A6ozsK30C6JG_xlJ56B8kwjUCuxDdnH3j10kp6cY',
    price: 13500,
    originalPrice: 15000,
    rating: 9.8,
    reviewsCount: 420,
    category: 'Literature',
    desc: '1980년 5월 18일부터 열흘간 있었던 광주민주화운동을 소재로 한 장편소설. 철저한 고증과 한강 작가 특유의 수려하고 가슴 시린 묘사로 폭력 한복판에 스러진 소년의 넋을 다룹니다.',
    descEn: 'A heart-wrenching novel exploring the 1980 Gwangju Democratic Uprising through connected characters. Deeply poetic and visceral exploration of human violence.',
    tag: 'Best',
    details: {
      isbn: '9788936434120',
      pages: 216,
      tableOfContents: [
        '1장: 새들의 은신처 (소년 동호)',
        '2장: 검은 숨 (영재와 영재의 친구)',
        '3장: 일곱 개의 뺨 (은숙 언니)',
        '4장: 쇠와 피 (임선생과 군인들)',
        '5장: 밤의 눈동자 (기한의 고통)',
        '6장: 꽃이 피는 쪽으로 (어머니)',
        '에필로그: 눈 덮인 등나무의 기억'
      ],
      authorIntro: '2024년 노벨문학상 수상자입니다. 인간의 조건, 상처의 연대, 그리고 육체와 영혼의 상호작용 속 극단적인 감정들을 날카롭고 시적인 언어로 탐닉하는 거장입니다.',
      authorIntroEn: 'Winner of the 2024 Nobel Prize in Literature. Her works deal with trauma, body-mind relationship, and deep humanitarian resilience.'
    }
  },
  {
    id: '채식주의자',
    title: '채식주의자',
    titleEn: 'The Vegetarian',
    author: '한강 지음',
    authorEn: 'Han Kang',
    publisher: '창비',
    publisherEn: 'Changbi',
    pubDate: '2007-10-30',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAP59JfoD4AriICpYsEgfYYp_zzWmGmCWsvc-nCBBIb166UDWHarEo2P_BBhMd4ZswSXr9iW1sYsAyAsOPLjslVAueTilhjGiJ83vWkymya6_-4z_UA4u8VfregWfZuqCxl9LH4cT6twwZLSJrcyxBIQ-x8mAf0f178F7_za1WWTEZAqn3JCtCnIx3HhFnRPj8jJbZv3Lxng-Eo6PJZXwK-pf3PNwnKLVMjpXnFLZnNjICuWmyPfSPyNAnh-WxuJF1KGJcVp2X-yD22',
    price: 12600,
    originalPrice: 14000,
    rating: 9.9,
    reviewsCount: 1028,
    category: 'Literature',
    desc: '어느 날 밤 기괴한 꿈을 꾼 후로 고기를 거부하며 스스로 정원 식물이 되어 간다고 믿는 주부 ‘영혜’의 기묘하고 어두운 변화. 세 가족 구성원들의 왜곡된 욕망과 일관된 폭력의 시선이 충돌합니다. 맨부커 국제상 수상작.',
    descEn: 'Winner of the International Booker Prize. A dense, elegant novel about Yeong-hye, who decides to completely reject meat, alienating her family.',
    tag: 'Classic',
    details: {
      isbn: '9788936433598',
      pages: 244,
      tableOfContents: [
        '1부: 채식주의자',
        '2부: 몽고반점',
        '3부: 나무 불꽃',
        '해설: 상처받은 짐승들의 몸짓',
        '작가의 기고문'
      ],
      authorIntro: '2024년 한국 최초로 노벨 문학상의 영예를 안았습니다. 상처를 대하는 시적이고 치열한 묘사는 세계인들에게 인간의 고통을 함께 나누는 거대한 연대를 선물합니다.',
      authorIntroEn: 'Awarded the Nobel Prize in Literature in 2024. Renowned worldwide for her deep thematic resonance, haunting imagery, and beautifully written books.'
    }
  },
  {
    id: '작별하지않는다',
    title: '작별하지 않는다',
    titleEn: 'We Do Not Part',
    author: '한강 지음',
    authorEn: 'Han Kang',
    publisher: '문학동네',
    publisherEn: 'Munhakdongne',
    pubDate: '2021-09-09',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCfcZ2C7pJ0H6rB4DDk918chOJHAYkGEpBDWivzj4AZIFrVLm_nDu-iDYpbVZIbstra0hLRzy-u1lSDyymZ-0rCzrsT4nYve5_wkxLAAj2QQakcyzyKlhhFD7Wv0M0a4UBykfyKjvj1gw4KpPD7x8qe-NAqk_Dct1HQEwA5wGUKMYLea_0lEdy7qpFGU7XgNFy8hhIQBTALnC_12u5AzmQY7cVJ2SSy1OZ90dPU9CiOtub6TxpTzmKLJToZiilRfi9LG5kbhO4hBGDS',
    price: 14400,
    originalPrice: 16000,
    rating: 9.2,
    reviewsCount: 156,
    category: 'Literature',
    desc: '눈 내리는 고요한 제주 섬. 억울하게 자행된 현대사의 비극 제주 4.3의 영혼들을 꿈과 환영, 깊고 맑은 사랑의 기도를 통해 부르는 한강 작가의 신화적이고 경이로운 구원 장편소설.',
    descEn: 'An ethereal novel traversing snow-covered Jeju, calling upon the souls of the historic Jeju April 3 incident with profound love and quiet mourning.',
    tag: 'New',
    details: {
      isbn: '9788954682152',
      pages: 332,
      tableOfContents: [
        '1부: 새',
        '2부: 밤',
        '3부: 실',
        '작가의 에세이',
        '발문: 영원히 타오르는 기억의 촛불'
      ],
      authorIntro: '2024 노벨 문학상 작가 한강의 가슴 떨리는 수려한 야심작. 역사에 겪는 큰 상처들을 외면하지 않고 연대의 수건으로 닦아내는 문학의 근원적 자세를 담았습니다.',
      authorIntroEn: 'Nobel laureate Han Kang has created a gorgeous novel combining historical trauma and the mystical boundaries of human fidelity.'
    }
  },
  {
    id: '생각의지도',
    title: '생각의 지도: 동양과 서양, 세상을 바라보는 서로 다른 시선',
    titleEn: 'The Geography of Thought: How Asians and Westerners Think Differently',
    author: '리처드 니스벳 지음 | 김희경 옮김',
    authorEn: 'Richard Nisbett',
    publisher: '김영사',
    publisherEn: 'Gimmyoung',
    pubDate: '2004-04-10',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCxrorAI29911PWfKF9ecA8jAiiLR8wJYWgGz4TSgJElgqdwqXi7xzaOZMUJAdqp9N_UhMs4SVDmXmojnhQYBYdiZdDU04mlJdEiiWB2rkUawqeIpxWNatexJvk9UtSR6NJuvUwVCkAJ96R0g5x5ZU0EiqS5375zGPxinXgx1Atn8h-dBzSgWDZgf-_CRCbk9_8tHZOyemsgY0CyjCA1br3tV83FAUk1c5R-ShT-wp3fk4Qo-vW34-g-0Obalk_cl6RUg8U434738I1',
    price: 16000,
    originalPrice: 16000,
    rating: 9.5,
    reviewsCount: 165,
    category: 'Literature', // fits general humanities but we map to Literature/Humanities
    desc: '동양과 서양의 근본적인 사고방식 차이를 물리학, 언어학, 역사학의 교차점에서 명쾌하고 풍성한 실험 자료를 토대로 입증한 심리학의 찬란한 고전입니다.',
    descEn: 'A brilliant psychological study demonstrating the core cognitive differences between Eastern relational focus and Western analytic behaviors.',
    tag: 'Must Read',
    details: {
      isbn: '9788934914197',
      pages: 284,
      tableOfContents: [
        '서문: 고대 그리스와 중국의 현대 유산',
        '1장. 동양의 기와 서양의 원자',
        '2장. 사회적 자아와 개별적 자아',
        '3장. 전체를 보는 동양과 부분을 보는 서양',
        '4장. 사물을 명사로 분류하는 서양과 관계로 묶는 동양',
        '5장. 인과적 진단 과정의 차이',
        '6장. 논리를 좋아하는 서양과 균형을 즐기는 동양',
        '7장. 동서양 사고방식의 미래'
      ],
      authorIntro: '미국 미시간 대학교 명예 교수이자 세계적인 사회심리학 분야의 석학입니다. 인간 이성, 문화적 프레이밍, 판단과 합리의 심리학적 오류에 관해 깊이 있게 연구했습니다.',
      authorIntroEn: 'Professor Emeritus of social psychology at University of Michigan, widely prized for analyzing cognitions, rationalization and choices.'
    }
  },
  // Adding Business books
  {
    id: '돈의속성',
    title: '돈의 속성 (300쇄 기념 에디션)',
    titleEn: 'The Property of Money',
    author: '김승호 지음',
    authorEn: 'Kim Seung-ho',
    publisher: '스노우폭스북스',
    publisherEn: 'Snowfox Books',
    pubDate: '2020-06-15',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC5GLYrn7Eky45Q_YFEbaLpbXvxExNb6b1kp4yxUhryb4JAqIOqFkHQIN87v8WVtqgn84E014FDoprIZzaGGJ5ppuyYWTMLapdKkkOLdV_qRqfceAyUxcuzZPhgOHT5GQeHA-hM8FWOKEePRhrORBW03KjsQC-Xt9gzxU2iNBg6yFUHgbWNRQS4rWHBxYrrx8SDjQL6YJ_lSAa3zUfyT6_usblF92siMXR7eNGFl5X3mft5T6AG6sy8FtUxuC7qvUKKGMR9L6xMcsEo', // Use high-quality placeholders or consistent images
    price: 15300,
    originalPrice: 17000,
    rating: 9.4,
    reviewsCount: 421,
    category: 'Business',
    desc: '돈은 인격체다. 돈은 자기가 대접받는 만큼 주인 곁을 지키며, 나쁜 사람을 응징하고, 소중히 아끼는 이에게 부귀를 선사한다. 자산가가 고르고 고른 평생 마인드 전수서.',
    descEn: 'A best-selling Korean guide on financial mastery, investing mindset and strategic wealth creation from a self-made global entrepreneur.',
    tag: 'Best'
  },
  {
    id: '부의시나리오',
    title: '부의 시나리오',
    titleEn: 'The Financial Scenario for Wealth',
    author: '오건영 지음',
    authorEn: 'Oh Geon-yeong',
    publisher: '페이지2',
    publisherEn: 'Page2',
    pubDate: '2021-06-10',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAMF2-vPWNbPAYHVpMexgSWJ7fxz3aKacHDynSg8SdrDqH0oQxYW8PJQI2SC8g2dyiJLqya5W96eeirkc5zzuDobOTt5Xti8dRrCT1h5CVSh3zMj9ZsnBwvKBhgijzxDW1mf5PXCJoazsnjmK4MhWbiWgzeaD_niLj0LeRtVK2TjTc8HZviOoGJDY4tjnvWofDkJw9XW4e_FJ7XwbE97p4m-IpHGGsCnHN9wyWTyvjfeSV0PTIP0jXvbrOqw-1vX3l9_kwww4tXdbWO',
    price: 16200,
    originalPrice: 18000,
    rating: 9.3,
    reviewsCount: 162,
    category: 'Business',
    desc: '인플레이션, 고금리, 저금리 상황 속에서 개인 투자자들이 어떻게 자산을 보호하고 기회를 잡을지 시나리오별로 탁월한 해석을 제공하는 거시경제 가이드북.',
    descEn: 'A macroeconomic roadmap preparing readers for variable inflation and global interest rate cycles with strategic action plans.',
    tag: 'Must Read'
  },
  // Adding Science books
  {
    id: '코스모스',
    title: '코스모스 (Cosmos)',
    titleEn: 'Cosmos',
    author: '칼 세이건 지음 | 홍승수 옮김',
    authorEn: 'Carl Sagan',
    publisher: '사이언스북스',
    publisherEn: 'Science Books',
    pubDate: '2006-12-10',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAGCXuTks7rl3QE0-b_wauD1uWO7FlCAtq7Jvwescjf2_WcSWqE3JBCUOmgeXgOMYafBtIvm_t9HTQycRr6zuAg5NXS6mDGpr7DTl_8zuqb4n1H9a-rY21OSpDthCnnpRchYuZzknEuPGvyZUE32G88biJQdv1jKteFyq4K__pjMrFqpbK4RmI8ZJFpKNzfpbB_bU3XOG8_-weeZCgaWiLqsnQ98kAUKjn1z3Jkz0GUd_Kq12PBY3PcKLeUhX4OQOsDY7R2V7c1sCqv',
    price: 19500,
    originalPrice: 19500,
    rating: 9.7,
    reviewsCount: 388,
    category: 'Science',
    desc: '우주의 탄생과 인류 문명, 생명의 진화를 과학적으로 풀어낸 역사상 최고의 대중과학서. 우리가 어디서 왔고 어디로 가야 하는지를 성성하고 빛나는 언어로 담아냈습니다.',
    descEn: 'The definitive astronomical classic exploring our place in the cosmic ocean, human civilization and stellar evolutions.',
    tag: 'Classic'
  },
  {
    id: '이기적유전자',
    title: '이기적 유전자',
    titleEn: 'The Selfish Gene',
    author: '리처드 도킨스 지음',
    authorEn: 'Richard Dawkins',
    publisher: '을유문화사',
    publisherEn: 'Eulyoo',
    pubDate: '2018-10-20',
    price: 20000,
    originalPrice: 20000,
    rating: 9.4,
    reviewsCount: 295,
    category: 'Science',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBytR-v5oOAjiLOdQbvEEFQMIN1NJ-Su1NOCQs4xmUG7hJSQ-DUH7v_lDtIQ0FwJZ2PqgeaMkHAG-fQzU6Z188LOs7hIiDBduHqQ5V0x_ZQA4cqulptBNGj0kVnh3eQODaU00wFLDMr_ZwBSD4MBmxZUWF8YhSh5BA9tZ2d4IheBcYK2FTP5hUX7WmP_gnKTxckfbdUA5_OemC1YwuTR0YVlA47WumfDnc9VnH-nCQ-mb8Un8QXiYvKa7RVCi4YhFGWAjr1n0CBqzUj',
    desc: '인간을 포함한 모든 생명체는 유전자의 지배를 받는 보존 전술적 탈것일 뿐이라는 도발적이며 찬란한 생물학적 패러다임을 던져 준 명불허전 고전입니다.',
    descEn: 'The revolutionary evolutionary biology masterwork defining life and altruism through the survival goals of genes.',
    tag: 'Best'
  },
  // Adding Arts books
  {
    id: '방구석미술관',
    title: '방구석 미술관: 가볍고 편하게 즐기는 유쾌한 미술야사',
    titleEn: 'Backroom Art Museum',
    author: '조원재 지음',
    authorEn: 'Cho Won-jae',
    publisher: '블랙피쉬',
    publisherEn: 'Black Fish',
    pubDate: '2018-08-03',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC6tW8uJU7-TBU4uukT_srEKC0yIE1b7RUmj3icXDNLp4jZap6hCd3MZA1LOxpNWr4u720O0lvhgDh6eUgK0oW6sCVciAJea2ohHFhNLCT-41KEUyblsgE3-nJ7Yx09kzyzH0K36k4Mjzqb_5yG2IUCDIs5WCI6sMRoBThkv91xSYYqyqFAJb41X2Nqcq5_wkJduUBaF1XDsVLaLHRqKwOmtSMsTgzFmjbF1N6nZtwPNRKYqpxvtdE8j7M75d-vBZNwUN2_CY5O118D',
    price: 15120,
    originalPrice: 16800,
    rating: 9.5,
    reviewsCount: 512,
    category: 'Arts',
    desc: '고흐, 마네, 피카소 등 교과서 밖 거장들의 인간미 물씬 풍기는 역사를 유쾌하게 풀어낸 베스트셀러. 미술에 대한 부담감을 단번에 지워 드리는 편안한 야사.',
    descEn: 'An accessible, warm and engaging tour of the art world, stripping away pretension to review the vibrant lives of classical masters.',
    tag: '10% Off'
  },
  // Adding Computers books
  {
    id: '클린코드',
    title: 'Clean Code 클린 코드: 애자일 소프트웨어 장인 정신',
    titleEn: 'Clean Code: A Handbook of Agile Software Craftsmanship',
    author: '로버트 C. 마틴 지음 | 박재호 옮김',
    authorEn: 'Robert C. Martin',
    publisher: '인사이트',
    publisherEn: 'Insight',
    pubDate: '2013-12-24',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC5GLYrn7Eky45Q_YFEbaLpbXvxExNb6b1kp4yxUhryb4JAqIOqFkHQIN87v8WVtqgn84E014FDoprIZzaGGJ5ppuyYWTMLapdKkkOLdV_qRqfceAyUxcuzZPhgOHT5GQeHA-hM8FWOKEePRhrORBW03KjsQC-Xt9gzxU2iNBg6yFUHgbWNRQS4rWHBxYrrx8SDjQL6YJ_lSAa3zUfyT6_usblF92siMXR7eNGFl5X3mft5T6AG6sy8FtUxuC7qvUKKGMR9L6xMcsEo',
    price: 29700,
    originalPrice: 33000,
    rating: 9.8,
    reviewsCount: 341,
    category: 'Computers',
    desc: '세계적인 소프트웨어 개발 전문가 밥 아저씨의 전설적인 명저. 가독성이 좋고, 안전하며 개조하기 수월한 훌륭한 코드를 저술하는 일관된 리팩토링 원칙 제공.',
    descEn: 'The software industry classic guide describing variables, functions, testing, and formatting elements to produce clean, maintainable systems.',
    tag: 'Classic'
  },
  // Adding Children books
  {
    id: '전천당1',
    title: '이상한 과자 가게 전천당 1',
    titleEn: 'Zenitendo: Mysterious Candy Shop Vol. 1',
    author: '히로시마 레이코 지음',
    authorEn: 'Hiroshima Reiko',
    publisher: '길벗스쿨',
    publisherEn: 'Gilbut School',
    pubDate: '2019-01-10',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBytR-v5oOAjiLOdQbvEEFQMIN1NJ-Su1NOCQs4xmUG7hJSQ-DUH7v_lDtIQ0FwJZ2PqgeaMkHAG-fQzU6Z188LOs7hIiDBduHqQ5V0x_ZQA4cqulptBNGj0kVnh3eQODaU00wFLDMr_ZwBSD4MBmxZUWF8YhSh5BA9tZ2d4IheBcYK2FTP5hUX7WmP_gnKTxckfbdUA5_OemC1YwuTR0YVlA47WumfDnc9VnH-nCQ-mb8Un8QXiYvKa7RVCi4YhFGWAjr1n0CBqzUj',
    price: 11700,
    originalPrice: 13000,
    rating: 9.6,
    reviewsCount: 412,
    category: 'Children',
    desc: '운이 좋은 사람만이 도달할 수 있는 신비한 과자가게 전천당. 손님들의 갖가지 고민과 상처를 마법의 과자를 통해 소망적이며 아름답게 해소해 주는 동화입니다.',
    descEn: 'A magical fantasy candy shop Zenitendo sells mysterious sweets that can solve any troubles for those lucky enough to locate it.',
    tag: '10% Off'
  }
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    user: '책좋아하는사람',
    rating: 5,
    comment: '깊은 여운과 전율이 일어나는 문장이 가득하네요. 시간 가는 줄 모르고 정독했습니다.',
    commentEn: 'This book moved me deeply. Every sentence is packed with delicate emotion and power.',
    date: '2026-05-18'
  },
  {
    id: 'rev-2',
    user: '인문학소년',
    rating: 5,
    comment: '정말 시의성 있고 가독성 좋은 최고의 책입니다. 지인들에게 가차 없이 선물할 생각이에요.',
    commentEn: 'What an incredible masterpiece. I am definitely introducing this as a gift to all my close friends.',
    date: '2026-05-29'
  },
  {
    id: 'rev-3',
    user: '라라베어',
    rating: 4,
    comment: '상처 입은 영혼들을 잔뜩 달래 주는 은혜로운 이야기입니다. 작가님의 다음 작품을 손꼽아 기다릴게요.',
    commentEn: 'Deeply comforting and beautifully written. Cant wait for the writers next journey.',
    date: '2026-06-02'
  },
  {
    id: 'rev-4',
    user: '바다의별',
    rating: 5,
    comment: '인간의 다층적인 심리를 이렇게 감성적이고 정교하게 풀어내다니, 인생 책 중 하나가 되었습니다.',
    commentEn: 'An absolute masterpiece of psychological prose. This instantly climbed to the top of my all-time favorites list.',
    date: '2026-06-07'
  }
];
